# Generated by Django 5.0.3 on 2024-03-14 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Figure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('lego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.lego', verbose_name='деталь')),
            ],
            options={
                'verbose_name': 'Фигура',
                'verbose_name_plural': 'Фигуры',
            },
        ),
    ]
